[package]
name = "nutype"
version = "0.1.0"
edition = "2021"

description = "Newtype library"
keywords = ["newtype"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nutype_macros = { path = "../nutype_macros" }
